enum Types {
  GET_ITEMS = 'GET_ITEMS',
  GET_ITEMS_COMPLETE = 'GET_ITEMS_COMPLETE',
  DELETE_ITEM = 'DELETE_ITEM',
  DELETE_ITEM_COMPLETE = 'DELETE_ITEM_COMPLETE',
  CREATE_ITEM = 'CREATE_ITEM',
  CREATE_ITEM_COMPLETE = 'CREATE_ITEM_COMPLETE',
  UPDATE_ITEM = 'UPDATE_ITEM',
  UPDATE_ITEM_COMPLETE = 'UPDATE_ITEM_COMPLETE',
  UPDATE_SIMULATED_AGE = 'UPDATE_SIMULATED_AGE',
}

export default Types;
