enum Types {
  UPDATE_ITEMS = 'UPDATE_ITEMS',
  UPDATE_ITEMS_COMPLETE = 'UPDATE_ITEMS_COMPLETE',
  DELETE_ITEM = 'DELETE_ITEM',
  DELETE_ITEM_COMPLETE = 'DELETE_ITEM_COMPLETE',
  CREATE_ITEM = 'CREATE_ITEM',
  CREATE_ITEM_COMPLETE = 'CREATE_ITEM_COMPLETE',
}

export default Types;
